### ISSUE TITLE
another bitcoin fork each day.....does this leave existing keys insecure?

### ISSUE THREAD

**Issue by johndpope** [LedgerHQ/ledger-wallet-api#15]
so in a few days there will be a new fork - bitcoin diamond following off the heels of bitcoin gold 
https://coinsutra.com/bitcoin-gold-ledger-wallet/

there's apps galore - but small question is  - should we blow away existing keys and move crypto out of wallets for safe keeping?

here's a following sceneario
user is told to claim coins
- user signs into nano 
-  there's an official app

https://businessdigit.com/the-bitcoin-gold-wallet-scam-sees-the-fraudsters-steal-3-2-million

"It is worth reminding everyone that it will never really be safe to enter your private key or mnemonic phrase for a pre-existing wallet on an online website. When you want to sweep out new coins from a pre-fork wallet address, the best practices are the same as for the other ranges: first send your old coins to a new wallet before you start. exposing the private keys of the original wallet Following this basic rule of private key management greatly reduces your risk of theft. "

I imagine that a bad fork could steal keys / is there some protection with ledger? 
I signed into nano ledger app on->  btg - but there was nothing there.

now I'm worried somehow my private keys leaked to them?
is that possible?

**Comment by matthewdowney** [comment]
If you're not going to try to access a fork via an untrusted application (you're not installing anything new on your ledger) there's no need to move anything—your coins are safe.

If you're going to try to access a fork via an untrusted application on your computer, the most it can do is request that the Ledger sign a transaction; it cannot see your private key. If it manages to sign a transaction that drains your wallet, it's the same effect. Transaction signatures (via the Bitcoin app anyhow) require your manual approval.

If you're going to install an untrusted application on your Ledger, that could be a problem.

**Comment by johndpope** [comment]
I still don't understand how the key can't be intercepted by nefarious block chain. 
If you have any links that describe this - please share.

**Comment by matthewdowney** [comment]
No key leaves your ledger. Your ledger has a key pair plus some additional entropy inside from which it derives keys for any number of cryptocurrencies. We can represent this as a tuple 
```
let seed = (K, k, c)
```
where _K_ is your public key and the other two are the private key & additional entropy. Your Ledger never provides access to anything other than _K_, with the exception of the setup phase where you write down a backup manually.

A computer has no visibility into this tuple, even if the code is malicious. When your computer requests a public address, instead of requesting the information inside of the ledger and using it to generate an address at the account level it does the opposite; it specifies what it wants to happen (address generation) and lets the ledger actually do this derivation internally.

This is the same for a transaction signature. There's some function _s(k, d) -> sig_ that takes the private key (_k_) and some data (_d_) & returns a signature (_sig_). There's another function that takes the seed tuple and generates a private key for some address _ckdpriv(k, c, i) -> k'_, where _(k, c)_ are the last two elements of the seed tuple, _i_ is just a number that says which key we want, and the returned value _k'_ is the key for a specific address, which is then used with our _s_ function.

If we had full visibility of the private keys, we'd compute something like this
```
let seed = (K, k, c)
let sig(address_number, transaction) = s(private_key, transaction)
   where private_key = ckdpriv(seed[1], seed[2], address_number)
```

Instead of asking the ledger for `seed`, or even for the result of `ckdpriv(seed[1], seed[2], address_number)`, we just build a function `sig(address_number, transaction)` and tell the ledger to fill in the blanks to use the private key, without ever revealing it to us.

The signature cannot be reversed to get your private key; this is why it is safe to allow nodes in the network to relay your signed transaction. The only risk is if you allow this whole process to take place with a `transaction` that you didn't actually create, say a `transaction` that send all _your_ money to someone else. This is not somebody stealing your key, but it's almost as bad. This can happen if you install software on your ledger that lies to you about the transaction you're signing, and then you don't check it before broadcasting.

**Comment by johndpope** [comment]
thanks @matthewdowney
