### ISSUE TITLE
Ledger.signP2PKH

### ISSUE THREAD

**Issue by droplister** [LedgerHQ/ledger-wallet-api#3]
I'm interested in using my Ledger as a keychain for signing raw txs, but theses txs are not multisig.

**Comment by btchip** [comment]
We support this in developer mode (see https://ledgerhq.github.io/btchip-doc/bitcoin-technical.html#_developer_mode_apdus) - we don't support it otherwise because then you could use the chip as an oracle to sign anything. The idea behind supporting it for P2SH is that the other party can still perform the validation.

**Comment by droplister** [comment]
I'm trying to use my Ledger with Counterparty XCP tokens which don't use P2SH txs yet.

Thanks for the link!

**Comment by btchip** [comment]
Regarding Counterparty you might prefer using our new APIs that'll soon be available for the Trustlet (TEE) application and upcoming hardware wallet products and let you code your own logic into the wallet itself. You can follow https://twitter.com/btchip and https://twitter.com/LedgerHQ to see when they are released.
